version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_SECRET}
      MYSQL_ROOT_PASSWORD: ${DB_SECRET}
  php:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        IMAGE_PHP_VERSION: ${IMAGE_PHP_VERSION}
    volumes:
      - .:/var/www/html
